echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "we are learning devsecops"
echo "we are learning git/github"
echo "we are complete the aws cloud"